### ISSUE TITLE
Quaternion_LookAt implementation

### ISSUE THREAD

**Issue by 4Bruno** [MartinWeigel/Quaternion#2]
Any chance you could show how to implement "LookAt" function using your library?

I tried rotating 2 quaternions (Q1 by yaw,Q2 by pitch) then multiplying together Quaternion_multiply(Q1,Q2,output);

For the yaw rotation works (quad mesh always facing me) but the pitch seems to be flipped.

**Comment by MartinWeigel** [comment]
I have not used this library in a while. But maybe have a look at: `void Quaternion_fromEulerZYX(double eulerZYX[3], Quaternion* output)`, which creates a Quaternion from three Euler angles.

If this does not help,  please post an example (with numbers) and your expected result.

**Comment by uhdcc** [comment]
to anybody having issues with pitch being flipped, i beleive this could be the issue : 


```
void Quaternion_toEulerZYX(Quaternion* q, double output[3])
{
    assert(output != NULL);

    // Roll (x-axis rotation)
    double sinr_cosp = +2.0 * (q->w * q->v[0] + q->v[1] * q->v[2]);
    double cosr_cosp = +1.0 - 2.0 * (q->v[0] * q->v[0] + q->v[1] * q->v[1]);
    output[0] = atan2(sinr_cosp, cosr_cosp);

    // Pitch (y-axis rotation)
    double sinp = +2.0 * (q->w * q->v[1] - q->v[2] * q->v[0]);
    if (fabs(sinp) >= 1)
        output[1] = copysign(M_PI / 2, sinp); // use 90 degrees if out of range
    else
        output[1] = asin(sinp);

    // Yaw (z-axis rotation)
    double siny_cosp = +2.0 * (q->w * q->v[2] + q->v[0] * q->v[1]);
    double cosy_cosp = +1.0 - 2.0 * (q->v[1] * q->v[1] + q->v[2] * q->v[2]);
    output[2] = atan2(siny_cosp, cosy_cosp);
}
```

particularly this line : 

`double sinp = +2.0 * (q->w * q->v[1] - q->v[2] * q->v[0]);`

the UnrealEngine equivalent is this:

`double sinp = +2.0 * (q->v[2] * q->v[0] - q->w * q->v[1]);`

which would give you flipped pitch output, im not really sure which one is technically correct

if you have access to UE repo :
https://github.com/EpicGames/UnrealEngine/blob/16dc333db3d6439c7f2886cf89db8907846c0e8a/Engine/Source/Runtime/Core/Private/Math/UnrealMath.cpp#L670

**Comment by uhdcc** [comment]
actually, i was just testing some other versions of this, and it seems like the UnrealEngine version is flipped the wrong way.

https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Quaternion_to_Euler_angles_(in_3-2-1_sequence)_conversion
