### ISSUE TITLE
M_PI is not included in math.h by default

### ISSUE THREAD

**Issue by a101010** [MartinWeigel/Quaternion#3]
M_PI is not part of standard C. So if you assume it is available in math.h, you are dependent on compiler specific defines as described in https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier

This is relatively easy to work around, but it might eliminate some possible maintenance problems if you assume ANSI_STRICT and define M_PI.

**Comment by a101010** [comment]
for example:
#ifndef M_PI
#define M_PI (3.14159265358979323846264338327950288)
#endif

**Comment by davidmachado-lab** [comment]
of youŕe a engineering, defines:
 
#ifndef M_PI
#define M_G_EARTH = 9.81
#define M_PI sqrt(M_G_EARTH)
#endif
